# 运行环境，监听端口
[server]
addr = ":8096"
app_name = "pontos-examples"
read_timeout = "5s"
write_timeout = "5s"
idle_timeout = "5s"

# 日志配置
[log]
# 日志输出目录，默认当前项目目录的logs目录
path = ""

[mysql]
host = "127.0.0.1"
port = 3306
user = "tal_example"
password = "tal_example_password"
database = "example"
charset = "utf8mb4"
loc = "Local"
read_timeout = "2s"
write_timeout = "2s"
#设置连接池中空闲连接的最大数量。
set_max_idle_conns = 200
#设置打开数据库连接的最大数量。
set_max_open_conns = 500
#设置连接可复用的最大时间,单位：秒
set_conn_max_lifetime = "120s"

[redis]
addr = "127.0.0.1:6379"
db = 0
auth = ""